export interface DSAProblem {
  id: number;
  name: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  week: 1 | 2 | 3 | 4 | 5;
  leetcodeUrl: string;
}

export const DSA_PROBLEMS: DSAProblem[] = [
  { id: 1, name: 'Two Sum', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/two-sum/' },
  { id: 2, name: 'Valid Anagram', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/valid-anagram/' },
  { id: 3, name: 'Contains Duplicate', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/contains-duplicate/' },
  { id: 4, name: 'Best Time to Buy and Sell Stock', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/' },
  { id: 5, name: 'Valid Palindrome', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/valid-palindrome/' },
  { id: 6, name: 'Longest Common Prefix', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/longest-common-prefix/' },
  { id: 7, name: 'Reverse String', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/reverse-string/' },
  { id: 8, name: 'Valid Parentheses', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/valid-parentheses/' },
  { id: 9, name: 'Merge Sorted Array', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/merge-sorted-array/' },
  { id: 10, name: 'Move Zeroes', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/move-zeroes/' },
  { id: 11, name: 'Plus One', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/plus-one/' },
  { id: 12, name: 'Roman to Integer', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/roman-to-integer/' },
  { id: 13, name: 'Palindrome Number', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/palindrome-number/' },
  { id: 14, name: 'Find the Index of First Occurrence', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/' },
  { id: 15, name: 'Length of Last Word', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/length-of-last-word/' },
  { id: 16, name: 'Search Insert Position', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/search-insert-position/' },
  { id: 17, name: 'Count and Say', difficulty: 'Medium', week: 1, leetcodeUrl: 'https://leetcode.com/problems/count-and-say/' },
  { id: 18, name: 'Missing Number', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/missing-number/' },
  { id: 19, name: 'Single Number', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/single-number/' },
  { id: 20, name: 'Climbing Stairs', difficulty: 'Easy', week: 1, leetcodeUrl: 'https://leetcode.com/problems/climbing-stairs/' },
  { id: 21, name: 'Group Anagrams', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/group-anagrams/' },
  { id: 22, name: 'Top K Frequent Elements', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/top-k-frequent-elements/' },
  { id: 23, name: 'Product of Array Except Self', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/product-of-array-except-self/' },
  { id: 24, name: 'Valid Sudoku', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/valid-sudoku/' },
  { id: 25, name: 'Encode and Decode Strings', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/encode-and-decode-strings/' },
  { id: 26, name: 'Longest Consecutive Sequence', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/longest-consecutive-sequence/' },
  { id: 27, name: 'Two Sum II', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/' },
  { id: 28, name: '3Sum', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/3sum/' },
  { id: 29, name: 'Container With Most Water', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/container-with-most-water/' },
  { id: 30, name: 'Trapping Rain Water', difficulty: 'Hard', week: 2, leetcodeUrl: 'https://leetcode.com/problems/trapping-rain-water/' },
  { id: 31, name: 'Max Number of K-Sum Pairs', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/max-number-of-k-sum-pairs/' },
  { id: 32, name: 'Subarray Sum Equals K', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/subarray-sum-equals-k/' },
  { id: 33, name: 'Minimum Size Subarray Sum', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/minimum-size-subarray-sum/' },
  { id: 34, name: 'Longest Substring Without Repeating Characters', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/' },
  { id: 35, name: 'Longest Repeating Character Replacement', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/longest-repeating-character-replacement/' },
  { id: 36, name: 'Permutation in String', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/permutation-in-string/' },
  { id: 37, name: 'Find All Anagrams in a String', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/find-all-anagrams-in-a-string/' },
  { id: 38, name: 'Minimum Window Substring', difficulty: 'Hard', week: 2, leetcodeUrl: 'https://leetcode.com/problems/minimum-window-substring/' },
  { id: 39, name: 'Sliding Window Maximum', difficulty: 'Hard', week: 2, leetcodeUrl: 'https://leetcode.com/problems/sliding-window-maximum/' },
  { id: 40, name: 'Best Time to Buy/Sell Stock II', difficulty: 'Medium', week: 2, leetcodeUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/' },
  { id: 41, name: 'Min Stack', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/min-stack/' },
  { id: 42, name: 'Longest Valid Parentheses', difficulty: 'Hard', week: 3, leetcodeUrl: 'https://leetcode.com/problems/longest-valid-parentheses/' },
  { id: 43, name: 'Evaluate Reverse Polish Notation', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/' },
  { id: 44, name: 'Generate Parentheses', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/generate-parentheses/' },
  { id: 45, name: 'Daily Temperatures', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/daily-temperatures/' },
  { id: 46, name: 'Car Fleet', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/car-fleet/' },
  { id: 47, name: 'Largest Rectangle in Histogram', difficulty: 'Hard', week: 3, leetcodeUrl: 'https://leetcode.com/problems/largest-rectangle-in-histogram/' },
  { id: 48, name: 'Maximum Depth of Binary Tree', difficulty: 'Easy', week: 3, leetcodeUrl: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/' },
  { id: 49, name: 'Same Tree', difficulty: 'Easy', week: 3, leetcodeUrl: 'https://leetcode.com/problems/same-tree/' },
  { id: 50, name: 'Invert Binary Tree', difficulty: 'Easy', week: 3, leetcodeUrl: 'https://leetcode.com/problems/invert-binary-tree/' },
  { id: 51, name: 'Max Difference Between Node and Ancestor', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/maximum-difference-between-node-and-ancestor/' },
  { id: 52, name: 'Diameter of Binary Tree', difficulty: 'Easy', week: 3, leetcodeUrl: 'https://leetcode.com/problems/diameter-of-binary-tree/' },
  { id: 53, name: 'Balanced Binary Tree', difficulty: 'Easy', week: 3, leetcodeUrl: 'https://leetcode.com/problems/balanced-binary-tree/' },
  { id: 54, name: 'Lowest Common Ancestor of BST', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/' },
  { id: 55, name: 'Binary Tree Level Order Traversal', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/binary-tree-level-order-traversal/' },
  { id: 56, name: 'Binary Tree Right Side View', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/binary-tree-right-side-view/' },
  { id: 57, name: 'Count Good Nodes in Binary Tree', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/' },
  { id: 58, name: 'Validate Binary Search Tree', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/validate-binary-search-tree/' },
  { id: 59, name: 'Kth Smallest Element in BST', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/' },
  { id: 60, name: 'Construct Binary Tree from Preorder and Inorder', difficulty: 'Medium', week: 3, leetcodeUrl: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/' },
  { id: 61, name: 'Binary Search', difficulty: 'Easy', week: 4, leetcodeUrl: 'https://leetcode.com/problems/binary-search/' },
  { id: 62, name: 'Search a 2D Matrix', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/search-a-2d-matrix/' },
  { id: 63, name: 'Koko Eating Bananas', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/koko-eating-bananas/' },
  { id: 64, name: 'Find Minimum in Rotated Sorted Array', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/' },
  { id: 65, name: 'Search in Rotated Sorted Array', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
  { id: 66, name: 'Time Based Key-Value Store', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/time-based-key-value-store/' },
  { id: 67, name: 'Find Median from Data Stream', difficulty: 'Hard', week: 4, leetcodeUrl: 'https://leetcode.com/problems/find-median-from-data-stream/' },
  { id: 68, name: 'Merge K Sorted Lists', difficulty: 'Hard', week: 4, leetcodeUrl: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
  { id: 69, name: 'Task Scheduler', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/task-scheduler/' },
  { id: 70, name: 'Design Twitter', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/design-twitter/' },
  { id: 71, name: 'Word Search', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/word-search/' },
  { id: 72, name: 'Number of Islands', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/number-of-islands/' },
  { id: 73, name: 'Rotting Oranges', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/rotting-oranges/' },
  { id: 74, name: 'Clone Graph', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/clone-graph/' },
  { id: 75, name: 'Pacific Atlantic Water Flow', difficulty: 'Medium', week: 4, leetcodeUrl: 'https://leetcode.com/problems/pacific-atlantic-water-flow/' },
  // Week 5 — Bonus 25 problems (Linked List, DP, Greedy, Backtracking)
  { id: 76, name: 'Reverse Linked List', difficulty: 'Easy', week: 5, leetcodeUrl: 'https://leetcode.com/problems/reverse-linked-list/' },
  { id: 77, name: 'Merge Two Sorted Lists', difficulty: 'Easy', week: 5, leetcodeUrl: 'https://leetcode.com/problems/merge-two-sorted-lists/' },
  { id: 78, name: 'Linked List Cycle', difficulty: 'Easy', week: 5, leetcodeUrl: 'https://leetcode.com/problems/linked-list-cycle/' },
  { id: 79, name: 'Reorder List', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/reorder-list/' },
  { id: 80, name: 'Remove Nth Node From End of List', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/' },
  { id: 81, name: 'Maximum Subarray', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/maximum-subarray/' },
  { id: 82, name: 'Coin Change', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/coin-change/' },
  { id: 83, name: 'House Robber', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/house-robber/' },
  { id: 84, name: 'House Robber II', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/house-robber-ii/' },
  { id: 85, name: 'Longest Increasing Subsequence', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/longest-increasing-subsequence/' },
  { id: 86, name: 'Decode Ways', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/decode-ways/' },
  { id: 87, name: 'Unique Paths', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/unique-paths/' },
  { id: 88, name: 'Jump Game', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/jump-game/' },
  { id: 89, name: 'Word Break', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/word-break/' },
  { id: 90, name: 'Combination Sum', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/combination-sum/' },
  { id: 91, name: 'Subsets', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/subsets/' },
  { id: 92, name: 'Permutations', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/permutations/' },
  { id: 93, name: 'Letter Combinations of a Phone Number', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/' },
  { id: 94, name: 'Course Schedule', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/course-schedule/' },
  { id: 95, name: 'Course Schedule II', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/course-schedule-ii/' },
  { id: 96, name: 'Implement Trie (Prefix Tree)', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/implement-trie-prefix-tree/' },
  { id: 97, name: 'Add and Search Words', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/' },
  { id: 98, name: 'Longest Palindromic Substring', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/longest-palindromic-substring/' },
  { id: 99, name: 'Palindromic Substrings', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/palindromic-substrings/' },
  { id: 100, name: 'Edit Distance', difficulty: 'Medium', week: 5, leetcodeUrl: 'https://leetcode.com/problems/edit-distance/' },
];
